// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagement.Data;

#nullable disable

namespace ProductManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagement.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nội thất phòng khách"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nội thất phòng ngủ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nội thất nhà bếp"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Đồ trang trí"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thiết bị thông minh"
                        });
                });

            modelBuilder.Entity("ProductManagement.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductName");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Sofa 3 chỗ ngồi thiết kế hiện đại, chất liệu da cao cấp",
                            ImgUrl = "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
                            Price = 15000000m,
                            ProductName = "Sofa hiện đại"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Bàn cà phê gỗ tự nhiên cao cấp, thiết kế tối giản",
                            ImgUrl = "https://images.unsplash.com/photo-1549497538-303791108f95?w=400",
                            Price = 3500000m,
                            ProductName = "Bàn cà phê gỗ"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Giường ngủ king size với đầu giường bọc da, khung gỗ sồi",
                            ImgUrl = "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400",
                            Price = 12000000m,
                            ProductName = "Giường ngủ king size"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Tủ quần áo 4 cánh gỗ công nghiệp, có gương và ngăn kéo",
                            ImgUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
                            Price = 8500000m,
                            ProductName = "Tủ quần áo"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Bộ bàn ăn 6 ghế gỗ sồi, thiết kế sang trọng",
                            ImgUrl = "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?w=400",
                            Price = 9500000m,
                            ProductName = "Bộ bàn ăn"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Kệ tivi gỗ công nghiệp, có ngăn chứa đồ",
                            ImgUrl = "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
                            Price = 4200000m,
                            ProductName = "Kệ tivi hiện đại"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Tủ bếp gỗ công nghiệp chống ẩm, mặt đá granite",
                            ImgUrl = "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
                            Price = 25000000m,
                            ProductName = "Tủ bếp cao cấp"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Đèn chùm pha lê cao cấp, ánh sáng LED",
                            ImgUrl = "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=400",
                            Price = 1800000m,
                            ProductName = "Đèn trang trí"
                        });
                });

            modelBuilder.Entity("ProductManagement.Models.Product", b =>
                {
                    b.HasOne("ProductManagement.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductManagement.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
